# PHP Configuration

---
- name: Install PHP
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql
  tags: [system]

- name: Install PHP extension
  apt: 
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ php_modules }}"
  tags: [php]
